name: testportal-prod

services:
  api:
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile
      target: production

    container_name: testportal-api-prod

    env_file:
      - ../../apps/api/.env

    # environment:
    #   DATABASE_URL: "postgresql://postgres:postgres@db:5432/testportal_dev"

    ports:
      - "3000:3000"

    restart: always

    # depends_on:
    #   db:
    #     condition: service_healthy

    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/api/health', r => process.exit(r.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"
        ]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

    networks:
      - testportal-network

  # db:
  #   image: postgres:16-alpine

  #   container_name: testportal-db-prod

  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: testportal_dev

  #   volumes:
  #     - testportal-prod-db-data:/var/lib/postgresql/data

  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   healthcheck:
  #     test:
  #       [
  #         "CMD-SHELL",
  #         "pg_isready -U postgres -d testportal_dev"
  #       ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  #   networks:
  #     - testportal-network

networks:
  testportal-network:
    driver: bridge

volumes:
  testportal-prod-db-data: